name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


env:
  # ——— Update these ———
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: my-node-app # your Cloud Run service name
  REGION: us-central1 # your Cloud Run region
  REPOSITORY: my-repo # your Artifact Registry repo
  IMAGE_URI: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/my-node-app

permissions:
  contents: read
  id-token: write

jobs:
  lint-test:
    name: 🧪 Lint & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: cd app && npm ci

      - name: Run lint
        run: cd app && npm run lint || echo "Lint script not found, skipping..."

      - name: Run unit tests
        run: cd app && npm test || echo "Test script not found, skipping..."

  build-and-scan:
    name: 🐳 Build Docker & Vulnerability Scan
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(node -p "require('./app/package.json').version")
          echo "Extracted version: $VERSION"
          if [ -z "$VERSION" ]; then
            echo "Warning: Version is empty, using default"
            VERSION="1.0.0"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & push multi-stage image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_URI }}:v${{ env.VERSION }}
            ${{ env.IMAGE_URI }}:latest
        env:
          DOCKER_BUILDKIT: 1

      - name: Verify image exists
        run: |
          echo "Checking if image exists: ${{ env.IMAGE_URI }}:v${{ env.VERSION }}"
          gcloud artifacts docker images describe ${{ env.IMAGE_URI }}:v${{ env.VERSION }} || echo "Image not found in registry"

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.IMAGE_URI }}:v${{ env.VERSION }}
          format: "table"
        continue-on-error: true

      - name: Ensure non-root user in Dockerfile
        run: |
          if grep -q '^USER root' Dockerfile; then
            echo "::error ::Dockerfile must specify a non-root USER"  
            exit 1
          fi

  deploy:
    name: 🚀 Deploy to Cloud Run
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(node -p "require('./app/package.json').version")
          echo "Extracted version: $VERSION"
          if [ -z "$VERSION" ]; then
            echo "Warning: Version is empty, using default"
            VERSION="1.0.0"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Deploy service
        run: |
          echo "VERSION env var: '${{ env.VERSION }}'"
          echo "Available images in repository:"
          gcloud artifacts docker images list us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/my-repo/my-node-app || echo "No images found"

          # Use latest tag if version is empty
          if [ -z "${{ env.VERSION }}" ]; then
            IMAGE_TAG="latest"
            echo "Using latest tag due to empty version"
          else
            IMAGE_TAG="v${{ env.VERSION }}"
            echo "Using version tag: $IMAGE_TAG"
          fi

          FULL_IMAGE="${{ env.IMAGE_URI }}:$IMAGE_TAG"
          echo "Deploying with image: $FULL_IMAGE"
          echo "Service: ${{ env.SERVICE }}"
          echo "Region: ${{ env.REGION }}"

          gcloud run deploy ${{ env.SERVICE }} \
            --image="$FULL_IMAGE" \
            --region=${{ env.REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --concurrency=80

      - name: Health check (uptime probe)
        run: |
          echo "Waiting for service to be ready..."
          sleep 30

          URL=$(gcloud run services describe ${{ env.SERVICE }} \
            --region=${{ env.REGION }} \
            --format="value(status.url)")

          echo "Service URL: $URL"

          for i in {1..5}; do
            echo "Health check attempt $i/5..."
            HTTP=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
            echo "HTTP response code: $HTTP"
            if [ "$HTTP" -eq 200 ]; then
              echo "✅ Health check passed"
              echo "🌐 Service URL: $URL"
              exit 0
            fi
            sleep 15
          done
          echo "❌ Health check failed after 5 attempts" && exit 1

      # — Manual rollback instructions (run locally) —
      # gcloud run services update-traffic ${{ env.SERVICE }} \
      #   --to-revisions=SERVICE_REVISION_OLD=100
